---
title: "Untitled"
output: html_document
date: "2024-09-24"
---

```{r setup, include=FALSE}
library(pxR)
library(dplyr)
library(tidyverse)

setwd("M:/Rudolph/0-Datasets/Switzerland")
```

```{r}
#Dataset source: Federal Statistical Office, https://www.bfs.admin.ch/asset/en/30445275
my.px.object <- read.px("px-x-1103020100_101.px")
my.data <- as.tibble(my.px.object) %>%
  rename(Jahr = Year)
```

```{r}
unique(my.data$Kanton)
```

```{r charging occupancy}
CH_sessions <- read.csv("C:/Users/santar_r/Documents/Rudolph_local/Python/EVSE-Status-Data/evse_statuses_2024-10-03_18h.csv")


```

```{r chargepoint details}
CH_EVSE_details <- read.csv("C:/Users/santar_r/Documents/Rudolph_local/Python/EVSE-Status-Data/EVSE_details_2024-10-04h.csv") %>%
  mutate(Power_kW = as.integer(sub("^(\\d+).*", "\\1", ChargingFacilities)))

CH_EVSE_details_short <- CH_EVSE_details %>%
  select(EvseID, ChargingStationId, ChargingFacilities, Power_kW, Accessibility, City, GeoCoordinates)

```


```{r}
charge.points.data <- read.csv("M:/Rudolph/0-Datasets/Switzerland/Swiss-chargers.csv")
```


```{r function to convert charging availability tables}

EVSE_processing <- function(csv_file, merged_object = NULL, id_col = "EvseID") { #file path as a string input
  # Read the csv file into a dataframe object
  my.df <- read.csv(csv_file)
  
  # Convert the availability statuses into factors (to save storage space)
  factor_cols <- 2:dim(my.df)[2]
  my.df[ , factor_cols] <- lapply(my.df[ , factor_cols],factor)

  # (Optional) Merge with an existing object
  if(!is.null(merged_object)) {
    result.df <- merge(merged_object, my.df, by = id_col, all = TRUE)
    return(result.df) #return a merged dataframe if one is defined
  }
  return(my.df) #return the single processed data frame
}

```

```{r function to cycle through files in a folder}
read_csvs <- function(main_dir = "C:/Users/santar_r/Documents/Rudolph_local/Python/EVSE-Status-Data") {
  # Get list of sub-directories in the main directory
  # subdirs <- list.dirs(main_dir, full.names = TRUE, recursive = FALSE)
  
  # Get list of files in the main directory
  file_list <- list.files(main_dir, pattern = "evse_statuses_")
  
  df_full <- NULL #initiate NULL for the dataframe
  
  # Loop through each sub directory
  for (file in file_list) {

    # Create the full path to the CSV file
    csv_file_path <- file.path(main_dir, file)
    
    if(is.null(df_full)) { #the first time this is run, df_full will be NULL
      # Read and process the csv
      df_full <- EVSE_processing(csv_file_path)
    } else {
      # Read, process, and merge the csv with existing ones
      df_full <- EVSE_processing(csv_file_path, df_full)
    }
    
  }
  
  return(df_full)
}

# Example usage:
# data_list <- read_csvs_from_folders("C:/Users/santar_r/Documents/Rudolph_local/Python/EVSE-Status-Data", "evse_statuses_")

```

```{r create joined df with all availability statuses}
#takes a few minutes to run
EVSE_df <- read_csvs()

```

```{r Utilization rate}

Util_rate <- function(df_input) { #takes the df object from function "read_csvs()" as the input
  df_util <- data.frame(timestamp = NA, year = NA, month = NA, day = NA, weekday = NA, hour = NA, minute = NA, occupied = NA, available = NA, unknown = NA, total = NA, utilization = NA)
  for(col in colnames(df_input[-1])) {
    num_used <- sum(df_input[ ,col] == "Occupied", na.rm = TRUE) #number of occupied CPs
    num_available <- sum(df_input[ ,col] == "Available", na.rm = TRUE) #number of available CPs
    num_unknown <- sum(df_input[ ,col] == "Unknown", na.rm = TRUE) #number of unknown CPs
    tot_num <- length(df_input[ ,col])
    
    utilization_rate <- num_used/tot_num
    
    #convert column name to a datetime object
    datetime_string <- sub("S_","",col)
    datetime_object <- ymd_hms(gsub("\\.", ":", datetime_string), tz = "Europe/Zurich")
    
    #record the data in a new results dataframe
    row_util <- data.frame(timestamp = datetime_object,
                           year = year(datetime_object), 
                           month = month(datetime_object),
                           day = day(datetime_object),
                           weekday = wday(datetime_object),
                           hour = hour(datetime_object),
                           minute = round(minute(datetime_object)/5)*5,
                           occupied = num_used, 
                           available = num_available, 
                           unknown = num_unknown, 
                           total = tot_num, 
                           utilization = utilization_rate)
    
    #bind with the large df
    df_util <- rbind(df_util, row_util)
  }
  return(df_util)
}

```

```{r Utilization rate values}
#takes some time to run
EVSE_util_df <- Util_rate(EVSE_df)

```
```{r clean data}
EVSE_util_df_cleaned <- EVSE_util_df %>%
  filter(unknown < 1000) #remove instances where 'unknown' CPs are too high, this is likely a data collection error

```

```{r plot utilization}
plot(x = as.POSIXlt(EVSE_util_df_cleaned$timestamp), y = EVSE_util_df_cleaned$utilization, pch = 19,
     ylab = "Utilization Rate", xlab = "Date", ylim = c(0,0.25))

```

```{r EVSE details}

Power_demand <- function(Charger_df, Status_df) {
  Charger_df <- Charger_df %>%
    select(EvseID, Power_kW)
  
  # Add the power demand column to the status data frame
  Power_status_df <- merge(Charger_df, Status_df, by = "EvseID", all = TRUE)
  
  # convert "occupied" into the power level for all the status columns
 for(col in 3:dim(Power_status_df)[2]) {
   Power_status_df[ , col] <- Power_status_df[ , "Power_kW"] * as.numeric(Power_status_df[ , col] == "Occupied")
 }
  return(Power_status_df) 
}

```

```{r convert statuses into power level demands}
Power_status_df <- Power_demand(CH_EVSE_details_short, EVSE_df)
```
```{r clean power status}
Power_status_df_cleaned <- Power_status_df %>%
  filter(!is.na(Power_kW))
```


```{r power level}
Power_level <- function(df_input, filters = NULL) { #takes the df object from function "Power_demand()" as the input
  df_power <- data.frame(timestamp = NA, year = NA, month = NA, day = NA, weekday = NA, hour = NA, minute = NA, power = NA)
  for(col in colnames(df_input[-c(1:2)])) {
    power_dem <- sum(df_input[ , col], na.rm = TRUE) #gets the total power level
    
    #convert column name to a datetime object
    datetime_string <- sub("S_","",col)
    datetime_object <- ymd_hms(gsub("\\.", ":", datetime_string), tz = "Europe/Zurich")
    
    #record the data in a new results dataframe
    row_pwr <- data.frame(timestamp = datetime_object,
                           year = year(datetime_object), 
                           month = month(datetime_object),
                           day = day(datetime_object),
                           weekday = wday(datetime_object),
                           hour = hour(datetime_object),
                           minute = round(minute(datetime_object)/5)*5,
                           power = power_dem)
    
    #bind with the large df
    df_power <- rbind(df_power, row_pwr)
  }
  return(df_power)
}

```

```{r power level data}
#takes time to run
Power_results <- Power_level(Power_status_df_cleaned)
```
```{r power level data cleaned}
Power_results_cleaned <- Power_results %>%
  filter(power > 0)

```


```{r plot power}
plot(x = as.POSIXlt(Power_results_cleaned$timestamp), y = Power_results_cleaned$power/1000, pch = 19,
     ylab = "Power Demand [MW]", xlab = "Date", ylim = c(0,20))
```

